## Waniya Munawwar

1. List all cities where the area is greater than 5000, along with their population.

In [15]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("factbook.db")

In [16]:
pd.read_sql_query("PRAGMA table_info(facts);", conn)

    cid               name          type  notnull dflt_value  pk
0     0                 id       INTEGER        1       None   1
1     1               code  varchar(255)        1       None   0
2     2               name  varchar(255)        1       None   0
3     3               area       INTEGER        0       None   0
4     4          area_land       INTEGER        0       None   0
5     5         area_water       INTEGER        0       None   0
6     6         population       INTEGER        0       None   0
7     7  population_growth         float        0       None   0
8     8         birth_rate         float        0       None   0
9     9         death_rate         float        0       None   0
10   10     migration_rate         float        0       None   0

In [17]:
query = """
SELECT name, population
FROM facts
WHERE area > 5000;
"""

In [18]:
pd.read_sql_query(query, conn)

                                  name  population
0                          Afghanistan  32564342.0
1                              Albania   3029278.0
2                              Algeria  39542166.0
3                               Angola  19625353.0
4                            Argentina  43431886.0
..                                 ...         ...
168     British Indian Ocean Territory         NaN
169  Falkland Islands (Islas Malvinas)      3361.0
170                        Puerto Rico   3598357.0
171                          West Bank   2785366.0
172                     Western Sahara    570866.0

[173 rows x 2 columns]

2. List the names of capital cities where the death rate is greater than 2% and the
birth rate is less than 20%

In [27]:
pd.read_sql_query("""
SELECT cities.name
FROM cities
JOIN facts
ON cities.facts_id = facts.id
WHERE cities.capital = 1
AND facts.death_rate > 2
AND facts.birth_rate < 20;
""", conn)

                 name
0          Oranjestad
1        Saint John'S
2                Baku
3              Tirana
4             Yerevan
..                ...
123         Road Town
124             Hanoi
125  Charlotte Amalie
126          Windhoek
127          Mata-Utu

[128 rows x 1 columns]

3. List the cities with a population growth rate between 1% and 5%, sorted in desc
by population growth.

In [28]:
pd.read_sql_query("""
SELECT cities.name, facts.population_growth
FROM cities
JOIN facts
ON cities.facts_id = facts.id
WHERE facts.population_growth BETWEEN 1 AND 5
ORDER BY facts.population_growth DESC;
""", conn)

          name  population_growth
0         Juba               4.02
1     Lilongwe               3.32
2    Bujumbura               3.28
3       Niamey               3.25
4      Kampala               3.24
..         ...                ...
210        Fes               1.00
211  Marrakech               1.00
212    Tangier               1.00
213     Agadir               1.00
214    Managua               1.00

[215 rows x 2 columns]

4. Find countries that start with &quot;A&quot; and do not have any cities listed in the cities
table. The query should return the country name and city name. Using left join

In [29]:
pd.read_sql_query("""
SELECT facts.name AS country_name,
       cities.name AS city_name
FROM facts
LEFT JOIN cities
ON facts.id = cities.facts_id
WHERE facts.name LIKE 'A%'
AND cities.id IS NULL;
""", conn)

                  country_name city_name
0  Ashmore and Cartier Islands      None
1                     Akrotiri      None
2                   Antarctica      None
3                 Arctic Ocean      None
4               Atlantic Ocean      None

5. List all capital cities and their corresponding death rate using a LEFT JOIN.

In [30]:
pd.read_sql_query("""
SELECT cities.name AS capital_city,
       facts.death_rate
FROM cities
LEFT JOIN facts
ON cities.facts_id = facts.id
WHERE cities.capital = 1;
""", conn)

     capital_city  death_rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]

## Completed